"""empty message

Revision ID: d23018721c11
Revises: 
Create Date: 2024-11-15 18:32:35.071230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23018721c11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pms_request_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile_no', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('fname', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pms_request_account')
    # ### end Alembic commands ###
